import imp, shutil, os

fp = open('submit.cgi')
pathname = 'submit.py'
description = ('.cgi', 'r', imp.PY_SOURCE)

mod = imp.load_module('submit', fp, pathname, description)

print mod, dir(mod)

try:
    shutil.rmtree('tmp_testdir')
except OSError:
    pass

s = """>query
MEEQQPEPKSQRDSGLGAVAAAAPSGLSLSLSPGASGSSGSDGDSVPVSPQPAPPSPPAAPCLPPLAHHPHLPPHPPPPPPPPPPPPQHLAAPAHQPQPAAQLHRTTNFFIDNILRPDFGCKKEQPLPQLLVASAAAGGGAAAGGGSRVERDRGQTGAGRDPVHSLGTRASGAASLLCAPDANCGPPDGSQPATAVGAGASKAGNPAAAAAAAAAAAAAAVAAAAAAASKPSDSGGGSGGNAGSPGAQGAKFPEHNPAILLMGSANGGPVVKTDSQQPLVWPAWVYCTRYSDRPSSGPRTRKLKKKKNEKEDKRPRTAFTAEQLQRLKAEFQANRYITEQRRQTLAQELSLNESQIKIWFQNKRAKIKKATGIKNGLALHLMAQGLYNHSTTTVQDKDESE"""

os.mkdir('tmp_testdir')
open('tmp_testdir/query.fa', 'w').write(s)
mod.worker_fn('tmp_testdir', 'protein')
